/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const init: () => void;
export const argb_array: () => any;
export const update_waveform: (a: any, b: number) => void;
export const tick: () => void;
export const reset: () => void;
export const __wbg_waveformparams_free: (a: number, b: number) => void;
export const __wbg_get_waveformparams_amplitude: (a: number) => number;
export const __wbg_set_waveformparams_amplitude: (a: number, b: number) => void;
export const __wbg_get_waveformparams_freq: (a: number) => number;
export const __wbg_set_waveformparams_freq: (a: number, b: number) => void;
export const __wbg_get_waveformparams_phase: (a: number) => number;
export const __wbg_set_waveformparams_phase: (a: number, b: number) => void;
export const __wbg_get_waveformparams_offset: (a: number) => number;
export const __wbg_set_waveformparams_offset: (a: number, b: number) => void;
export const __wbg_get_waveformparams_dt: (a: number) => number;
export const __wbg_set_waveformparams_dt: (a: number, b: number) => void;
export const waveformparams_new: (a: number, b: number, c: number, d: number, e: number) => number;
export const waveformparams_get: (a: number) => number;
export const waveformparams_set_dt: (a: number, b: number) => void;
export const waveformparams_set_amplitude: (a: number, b: number) => void;
export const waveformparams_set_freq: (a: number, b: number) => void;
export const waveformparams_set_phase: (a: number, b: number) => void;
export const waveformparams_set_offset: (a: number, b: number) => void;
export const waveformparams_set: (a: number, b: number) => void;
export const waveformparams_get_amplitude: (a: number) => number;
export const waveformparams_get_freq: (a: number) => number;
export const waveformparams_get_phase: (a: number) => number;
export const waveformparams_get_offset: (a: number) => number;
export const waveformparams_get_dt: (a: number) => number;
export const __wbindgen_export_0: WebAssembly.Table;
export const __wbindgen_start: () => void;
